### ISSUE TITLE
Checking for the deployment status too quick

### ISSUE THREAD

**Issue by jhutchinson-aritzia** [engswee/flashpipe#6]
Hello,

When using the "Deploy integration flow to runtime" step (script deploy_runtime_artifact.sh), I received a "404 Not Found" error in the workflow logs during the step to check on the deployment status.  The iFlow that I was deploying was not currently deployed in the runtime of SAP CI.  Using Postman to query for the deployment status after the workflow had failed, I was able to successfully retrieve the status of the iFlow and it had deployed successfully.  This leads me to believe that the code may be executing the status check request before the SAP CI tenant has updated the runtime with the new iFlow, causing a 404 error that cannot be recovered from in the 'getDetails' function of the class RuntimeArtifact.  I've included the log from my Github action workflow below.

I was wondering you would be open to inserting a delay prior to the check of the status of the deployment in order to mitigate this type of error?  Also, let me know if you need any further details from me.  Thanks!

### Github action workflow log
[INFO] Processing IFlow 1 - Test-IFow
[INFO] Comparing designtime version with runtime version
[INFO] 🚀 IFlow previously not deployed, or versions differ. Proceeding to deploy IFlow Test-IFow with version 1.0.2
[INFO] IFlow Test-IFow deployment triggered
[INFO] Checking deployment status for IFlow Test-IFow every 30 seconds up to 10 times
[ERROR] 🛑 Response body = {"error":{"code":"Not Found","message":{"lang":"en","value":"Requested entity could not be found."}}}
Exception in thread "main" io.github.engswee.flashpipe.http.HTTPExecuterException: Get runtime artifact call failed with response code = 404
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:77)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:238)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:250)
	at io.github.engswee.flashpipe.http.HTTPExecuter.logError(HTTPExecuter.groovy:42)
	at io.github.engswee.flashpipe.http.HTTPExecuter$logError$1.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
	at io.github.engswee.flashpipe.cpi.api.RuntimeArtifact.getDetails(RuntimeArtifact.groovy:55)
	at io.github.engswee.flashpipe.cpi.api.RuntimeArtifact.getStatus(RuntimeArtifact.groovy:19)
	at io.github.engswee.flashpipe.cpi.api.RuntimeArtifact$getStatus$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
	at io.github.engswee.flashpipe.cpi.exec.DeployDesignTimeArtifact.checkDeploymentStatus(DeployDesignTimeArtifact.groovy:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:352)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:68)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:157)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:193)
	at io.github.engswee.flashpipe.cpi.exec.DeployDesignTimeArtifact$_execute_closure2.doCall(DeployDesignTimeArtifact.groovy:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.Closure.call(Closure.java:420)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.eachWithIndex(DefaultGroovyMethods.java:2041)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.eachWithIndex(DefaultGroovyMethods.java:2021)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.eachWithIndex(DefaultGroovyMethods.java:2071)
	at org.codehaus.groovy.runtime.dgm$175.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
	at io.github.engswee.flashpipe.cpi.exec.DeployDesignTimeArtifact.execute(DeployDesignTimeArtifact.groovy:41)
	at io.github.engswee.flashpipe.cpi.exec.DeployDesignTimeArtifact$execute.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
	at io.github.engswee.flashpipe.cpi.exec.DeployDesignTimeArtifact.main(DeployDesignTimeArtifact.groovy:18)
Error: Process completed with exit code 1.

**Comment by engswee** [comment]
Hi @jhutchinson-aritzia , thanks for reporting this issue. Indeed this is an issue that was unintentionally introduced during the last release - I refactored some code and the delay part wasn't done correctly. I'll correct that delay part so that there is some gap before the check is performed.

**Comment by engswee** [comment]
Hi @jhutchinson-aritzia , I've released a new version which has the delay incorporated. If you are using the rolling tags, i.e. `2.x.x`, then you should get the change immediately on your next pipeline run. Let me know if you still encounter the issue.

**Comment by jhutchinson-aritzia** [comment]
Hi @engswee, your fix worked like a charm!  Was able to deploy an iFlow that was previously undeployed using GitHub Actions.

Amazing work you've done here!

**Comment by engswee** [comment]
Great, glad to hear it's working fine for you now. Thanks for the confirmation.
